/**
 * MioClean Product Catalog
 * Distribuidora de artículos de limpieza
 */

const products = [
  {
    id: "MC-001",
    name: "Detergente Líquido Lavarropas 1L",
    nameEn: "Laundry Liquid Detergent 1L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 3.99,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 120,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-002",
    name: "Detergente Líquido Lavarropas 3L",
    nameEn: "Laundry Liquid Detergent 3L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 10.5,
    unit: "envase 3L",
    unitEn: "3L container",
    sizeL: 3,
    stock: 85,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "3l", "3 litros"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-003",
    name: "Detergente Líquido Lavarropas 5L",
    nameEn: "Laundry Liquid Detergent 5L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 15.99,
    unit: "galón 5L",
    unitEn: "5L gallon",
    sizeL: 5,
    stock: 60,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "5l", "5 litros"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-004",
    name: "Cloro Líquido 1L",
    nameEn: "Liquid Bleach 1L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 2.5,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 150,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-005",
    name: "Cloro Líquido 3L",
    nameEn: "Liquid Bleach 3L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 6.75,
    unit: "envase 3L",
    unitEn: "3L container",
    sizeL: 3,
    stock: 110,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "3l", "3 litros"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-006",
    name: "Cloro Líquido 5L",
    nameEn: "Liquid Bleach 5L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 9.99,
    unit: "galón 5L",
    unitEn: "5L gallon",
    sizeL: 5,
    stock: 70,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "5l", "5 litros"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-007",
    name: "Suavizante de Ropa 1L",
    nameEn: "Fabric Softener 1L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 3.25,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 100,
    description: "Suavizante para ropa con fragancia fresca y duradera.",
    descriptionEn: "Fabric softener with fresh long-lasting fragrance.",
    tags: ["suavizante", "ropa", "lavandería", "fabric softener", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/a4574855-d9fa-4161-9e85-f3e65b2abcfc",
  },
  {
    id: "MC-008",
    name: "Suavizante de Ropa 3L",
    nameEn: "Fabric Softener 3L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 8.5,
    unit: "envase 3L",
    unitEn: "3L container",
    sizeL: 3,
    stock: 90,
    description: "Suavizante para ropa con fragancia fresca y duradera.",
    descriptionEn: "Fabric softener with fresh long-lasting fragrance.",
    tags: ["suavizante", "ropa", "lavandería", "fabric softener", "3l", "3 litros"],
    image: "https://github.com/user-attachments/assets/a4574855-d9fa-4161-9e85-f3e65b2abcfc",
  },
  {
    id: "MC-009",
    name: "Suavizante de Ropa 5L",
    nameEn: "Fabric Softener 5L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 12.99,
    unit: "galón 5L",
    unitEn: "5L gallon",
    sizeL: 5,
    stock: 55,
    description: "Suavizante para ropa con fragancia fresca y duradera.",
    descriptionEn: "Fabric softener with fresh long-lasting fragrance.",
    tags: ["suavizante", "ropa", "lavandería", "fabric softener", "5l", "5 litros"],
    image: "https://github.com/user-attachments/assets/a4574855-d9fa-4161-9e85-f3e65b2abcfc",
  },
];

const categories = Array.from(
  new Map(products.map((p) => [p.category, { id: p.category, name: p.category, nameEn: p.categoryEn }])).values()
);

module.exports = { products, categories };
