/**
 * MioClean Product Catalog
 * Distribuidora de artículos de limpieza
 */

const products = [
  {
    id: "MC-001",
    name: "Detergente Líquido Lavarropas 1L",
    nameEn: "Laundry Liquid Detergent 1L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 3.99,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 120,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-002",
    name: "Detergente Líquido Lavarropas 3L",
    nameEn: "Laundry Liquid Detergent 3L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 10.5,
    unit: "envase 3L",
    unitEn: "3L container",
    sizeL: 3,
    stock: 85,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "3l", "3 litros"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-003",
    name: "Detergente Líquido Lavarropas 5L",
    nameEn: "Laundry Liquid Detergent 5L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 15.99,
    unit: "galón 5L",
    unitEn: "5L gallon",
    sizeL: 5,
    stock: 60,
    description: "Jabón + suavizante para ropa blanca, de color y de bebé.",
    descriptionEn: "Soap + softener for white, color and baby clothes.",
    tags: ["detergente", "lavarropas", "jabón", "suavizante", "ropa", "5l", "5 litros"],
    image: "https://github.com/user-attachments/assets/de7ac6b0-55e7-4326-81c7-0043d0034d21",
  },
  {
    id: "MC-004",
    name: "Cloro Líquido 1L",
    nameEn: "Liquid Bleach 1L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 2.5,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 150,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-005",
    name: "Cloro Líquido 3L",
    nameEn: "Liquid Bleach 3L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 6.75,
    unit: "envase 3L",
    unitEn: "3L container",
    sizeL: 3,
    stock: 110,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "3l", "3 litros"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-003",
    name: "Jabón Líquido Multiuso 2L",
    nameEn: "Multi-Purpose Liquid Soap 2L",
    category: "jabones",
    categoryEn: "soaps",
    brand: "Mio Clean",
    price: 8.4,
    unit: "botella 2L",
    unitEn: "2L bottle",
    sizeL: 2,
    stock: 92,
    description: "Jabón multiuso para limpieza general, cocina y baños.",
    descriptionEn: "General-purpose soap for cleaning kitchens and bathrooms.",
    tags: ["jabón", "multiuso", "limpieza", "cocina", "baño", "2l"],
    image: "https://github.com/user-attachments/assets/3f4db4c7-8d37-4806-9b0d-f5c5d4d7d3c9",
  },
  {
    id: "MC-004",
    name: "Desengrasante Industrial 5L",
    nameEn: "Industrial Degreaser 5L",
    category: "desengrasantes",
    categoryEn: "degreasers",
    brand: "Mio Clean",
    price: 14.5,
    unit: "bidón 5L",
    unitEn: "5L drum",
    sizeL: 5,
    stock: 54,
    description: "Solución potente para superficies con grasa y suciedad intensa.",
    descriptionEn: "Powerful solution for greasy and heavily soiled surfaces.",
    tags: ["desengrasante", "industrial", "grasa", "limpieza", "5l"],
    image: "https://github.com/user-attachments/assets/7b34d0db-ffec-4c86-9fcd-4d37aeb1eb35",
  },
  {
    id: "MC-005",
    name: "Papel Higiénico 12 Rollos",
    nameEn: "Toilet Paper 12 Rolls",
    category: "papel",
    categoryEn: "paper",
    brand: "Mio Clean",
    price: 11.2,
    unit: "pack 12 rollos",
    unitEn: "12-roll pack",
    sizeL: 12,
    stock: 120,
    description: "Papel higiénico suave y absorbente para uso doméstico y comercial.",
    descriptionEn: "Soft and absorbent toilet paper for home and commercial use.",
    tags: ["papel", "higiénico", "rollos", "baño", "suave"],
    image: "https://github.com/user-attachments/assets/8d52e64c-b1d5-4214-b56f-7451f2e3fceb",
  },
  {
    id: "MC-006",
    name: "Cloro Líquido 5L",
    nameEn: "Liquid Bleach 5L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 9.99,
    unit: "galón 5L",
    unitEn: "5L gallon",
    sizeL: 5,
    stock: 70,
    description: "Cloro concentrado para desinfección y blanqueo.",
    descriptionEn: "Concentrated bleach for disinfection and whitening.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "5l", "5 litros"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  },
  {
    id: "MC-007",
    name: "Suavizante de Ropa 1L",
    nameEn: "Fabric Softener 1L",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "Mio Clean",
    price: 3.25,
    unit: "botella 1L",
    unitEn: "1L bottle",
    sizeL: 1,
    stock: 100,
    description: "Suavizante para ropa con fragancia fresca y duradera.",
    descriptionEn: "Fabric softener with fresh long-lasting fragrance.",
    tags: ["suavizante", "ropa", "lavandería", "fabric softener", "1l", "1 litro"],
    image: "https://github.com/user-attachments/assets/a4574855-d9fa-4161-9e85-f3e65b2abcfc",
  },
  {
    id: "MC-008",
    name: "Guantes de Nitrilo Talla L",
    nameEn: "Nitrile Gloves Size L",
    category: "proteccion",
    categoryEn: "protection",
    brand: "Mio Clean",
    price: 4.8,
    unit: "par",
    unitEn: "pair",
    sizeL: 1,
    stock: 150,
    description: "Guantes de nitrilo resistentes para limpieza y manejo seguro.",
    descriptionEn: "Durable nitrile gloves for cleaning and safe handling.",
    tags: ["guantes", "nitrilo", "protección", "seguridad", "limpieza"],
    image: "https://github.com/user-attachments/assets/3d58e967-7f93-4d2e-b0e8-e59a3b0f3ee6",
  },
  {
    id: "MC-009",
    name: "Escoba de Piso Profesional",
    nameEn: "Professional Floor Broom",
    category: "equipos",
    categoryEn: "equipment",
    brand: "Mio Clean",
    price: 18.2,
    unit: "unidad",
    unitEn: "unit",
    sizeL: 1,
    stock: 30,
    description: "Escoba robusta para limpieza de pisos de interior y exterior.",
    descriptionEn: "Robust broom for indoor and outdoor floor cleaning.",
    tags: ["escoba", "piso", "limpieza", "equipo", "profesional"],
    image: "https://github.com/user-attachments/assets/62f83a77-334d-4b5e-8f17-cf9932f4e9a5",
  },
  {
    id: "MC-010",
    name: "Cloro Líquido 10L",
    nameEn: "Liquid Bleach 10L",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "Mio Clean",
    price: 160,
    unit: "bidón 10L",
    unitEn: "10L container",
    sizeL: 10,
    stock: 40,
    description: "Cloro concentrado en bidón de 10 litros para uso industrial.",
    descriptionEn: "Concentrated bleach in 10-litre container for industrial use.",
    tags: ["cloro", "bleach", "desinfectante", "blanqueador", "10l", "10 litros", "bidon", "industrial"],
    image: "https://github.com/user-attachments/assets/242eb95e-b5e0-46db-bdae-47e4c6615c71",
  }
];

const categories = Array.from(
  new Map(products.map((p) => [p.category, { id: p.category, name: p.category, nameEn: p.categoryEn }])).values()
);

module.exports = { products, categories };
