/**
 * MioClean Product Catalog
 * Distribuidora de artículos de limpieza
 */

const products = [
  {
    id: "MC-001",
    name: "Detergente Multiusos Premium",
    nameEn: "Premium Multi-Purpose Detergent",
    category: "detergentes",
    categoryEn: "detergents",
    brand: "MioClean Pro",
    price: 45.99,
    unit: "galón",
    unitEn: "gallon",
    stock: 250,
    description: "Detergente concentrado para superficies industriales y del hogar.",
    descriptionEn: "Concentrated detergent for industrial and home surfaces.",
    tags: ["detergente", "multiusos", "limpieza", "industrial", "hogar"],
    image: "/images/detergente-premium.jpg",
  },
  {
    id: "MC-002",
    name: "Desinfectante Cloro Concentrado",
    nameEn: "Concentrated Chlorine Disinfectant",
    category: "desinfectantes",
    categoryEn: "disinfectants",
    brand: "MioClean Pro",
    price: 28.5,
    unit: "galón",
    unitEn: "gallon",
    stock: 180,
    description: "Cloro al 10% para desinfección profunda de áreas críticas.",
    descriptionEn: "10% chlorine for deep disinfection of critical areas.",
    tags: ["cloro", "desinfectante", "blanqueador", "limpieza", "bactericida"],
    image: "/images/cloro-concentrado.jpg",
  },
  {
    id: "MC-003",
    name: "Jabón Líquido de Manos Antibacterial",
    nameEn: "Antibacterial Liquid Hand Soap",
    category: "jabones",
    categoryEn: "soaps",
    brand: "MioClean Fresh",
    price: 12.99,
    unit: "litro",
    unitEn: "liter",
    stock: 400,
    description: "Jabón antibacterial con aloe vera para manos suaves y protegidas.",
    descriptionEn: "Antibacterial soap with aloe vera for soft, protected hands.",
    tags: ["jabón", "manos", "antibacterial", "aloe", "higiene"],
    image: "/images/jabon-antibacterial.jpg",
  },
  {
    id: "MC-004",
    name: "Limpiapisos Aromatizante",
    nameEn: "Aromatic Floor Cleaner",
    category: "limpiapisos",
    categoryEn: "floor cleaners",
    brand: "MioClean Fresh",
    price: 18.75,
    unit: "galón",
    unitEn: "gallon",
    stock: 320,
    description: "Limpiador de pisos con aroma a lavanda, deja brillante y perfumado.",
    descriptionEn: "Floor cleaner with lavender scent, leaves shiny and fragrant.",
    tags: ["limpiapisos", "piso", "lavanda", "aroma", "brillante"],
    image: "/images/limpiapisos.jpg",
  },
  {
    id: "MC-005",
    name: "Desengrasante Industrial",
    nameEn: "Industrial Degreaser",
    category: "desengrasantes",
    categoryEn: "degreasers",
    brand: "MioClean Industrial",
    price: 55.0,
    unit: "galón",
    unitEn: "gallon",
    stock: 120,
    description: "Desengrasante potente para cocinas industriales y talleres mecánicos.",
    descriptionEn: "Powerful degreaser for industrial kitchens and mechanical workshops.",
    tags: ["desengrasante", "grasa", "industrial", "cocina", "taller"],
    image: "/images/desengrasante.jpg",
  },
  {
    id: "MC-006",
    name: "Papel Higiénico Industrial (Caja x48)",
    nameEn: "Industrial Toilet Paper (Box x48)",
    category: "papel",
    categoryEn: "paper",
    brand: "MioClean Papel",
    price: 89.0,
    unit: "caja",
    unitEn: "box",
    stock: 95,
    description: "Papel higiénico doble hoja, 400 hojas por rollo, caja de 48 rollos.",
    descriptionEn: "Double-ply toilet paper, 400 sheets per roll, box of 48 rolls.",
    tags: ["papel", "higiénico", "rollo", "baño", "doble hoja"],
    image: "/images/papel-higienico.jpg",
  },
  {
    id: "MC-007",
    name: "Trapeador Mop Industrial",
    nameEn: "Industrial Mop",
    category: "equipos",
    categoryEn: "equipment",
    brand: "MioClean Tools",
    price: 34.99,
    unit: "unidad",
    unitEn: "unit",
    stock: 75,
    description: "Trapeador de microfibra con mango telescópico ajustable.",
    descriptionEn: "Microfiber mop with adjustable telescopic handle.",
    tags: ["trapeador", "mop", "microfibra", "piso", "limpieza"],
    image: "/images/trapeador.jpg",
  },
  {
    id: "MC-008",
    name: "Bolsas de Basura Negras (Paquete x100)",
    nameEn: "Black Garbage Bags (Pack x100)",
    category: "descartables",
    categoryEn: "disposables",
    brand: "MioClean Pack",
    price: 22.0,
    unit: "paquete",
    unitEn: "pack",
    stock: 500,
    description: "Bolsas de basura resistentes de 60 litros, paquete de 100 unidades.",
    descriptionEn: "Resistant 60-liter garbage bags, pack of 100 units.",
    tags: ["bolsas", "basura", "negro", "60 litros", "descartable"],
    image: "/images/bolsas-basura.jpg",
  },
  {
    id: "MC-009",
    name: "Guantes de Nitrilo (Caja x100)",
    nameEn: "Nitrile Gloves (Box x100)",
    category: "proteccion",
    categoryEn: "protection",
    brand: "MioClean Safe",
    price: 38.5,
    unit: "caja",
    unitEn: "box",
    stock: 210,
    description: "Guantes desechables de nitrilo sin polvo, talla M, L y XL disponibles.",
    descriptionEn: "Powder-free disposable nitrile gloves, sizes M, L and XL available.",
    tags: ["guantes", "nitrilo", "desechable", "protección", "latex free"],
    image: "/images/guantes-nitrilo.jpg",
  },
  {
    id: "MC-010",
    name: "Desodorante Ambiental Spray",
    nameEn: "Air Freshener Spray",
    category: "ambientadores",
    categoryEn: "air fresheners",
    brand: "MioClean Fresh",
    price: 8.99,
    unit: "unidad",
    unitEn: "unit",
    stock: 600,
    description: "Desodorante ambiental en spray con fragancia de cítricos, 400ml.",
    descriptionEn: "Citrus fragrance air freshener spray, 400ml.",
    tags: ["ambientador", "spray", "cítrico", "aroma", "desodorante"],
    image: "/images/ambientador.jpg",
  },
  {
    id: "MC-011",
    name: "Jabón en Polvo para Ropa",
    nameEn: "Laundry Powder Detergent",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "MioClean Wash",
    price: 32.0,
    unit: "bolsa 5kg",
    unitEn: "5kg bag",
    stock: 150,
    description: "Jabón en polvo para ropa con suavizante incorporado, aroma floral.",
    descriptionEn: "Laundry powder with built-in softener, floral fragrance.",
    tags: ["jabón", "polvo", "ropa", "lavandería", "suavizante"],
    image: "/images/jabon-polvo.jpg",
  },
  {
    id: "MC-012",
    name: "Suavizante de Ropa Concentrado",
    nameEn: "Concentrated Fabric Softener",
    category: "lavandería",
    categoryEn: "laundry",
    brand: "MioClean Wash",
    price: 19.5,
    unit: "galón",
    unitEn: "gallon",
    stock: 175,
    description: "Suavizante concentrado para ropa, reduce estática y deja suavidad.",
    descriptionEn: "Concentrated fabric softener, reduces static and leaves softness.",
    tags: ["suavizante", "ropa", "lavandería", "concentrado", "estática"],
    image: "/images/suavizante.jpg",
  },
];

const categories = [
  ...new Set(products.map((p) => ({ id: p.category, name: p.category, nameEn: p.categoryEn }))),
];

module.exports = { products, categories };
